[plugins]
spotless = { id = "com.diffplug.spotless", version = "8.0.0" }
springdependency = { id = "io.spring.dependency-management", version = "1.1.7" }
springboot = { id = "org.springframework.boot", version = "3.5.7" }
[libraries]
apachePDFBox = { module = "org.apache.pdfbox:pdfbox", version = "3.0.6" }
cdimascioDotenv = { module = "io.github.cdimascio:dotenv-java", version = "3.2.0" }
jakartaXML = { module = "jakarta.xml.bind:jakarta.xml.bind-api", version = "4.0.2" }
jlineJansi = { module = "org.jline:jansi", version = "3.30.4" }
heberModeloAPI = { module = "io.github.heberbarra:heber-modelo-api", version = "0.0.11-SNAP" }
hibernateCore = { module = "org.hibernate:hibernate-core", version = "7.1.6.Final" }
mysqlConnector = { module = "com.mysql:mysql-connector-j", version = "9.5.0" }
tomlj = { module = "org.tomlj:tomlj", version = "1.1.1" }
